streamify:
  outputs:
    dev:
      dataset: streamify_dev
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: dt-dta-adrien-sandbox-dev
      #project: "{{ env_var('DBT_GCP_PROJECT') }}"
      threads: 4
      type: bigquery
    prod:
      dataset: streamify
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: dt-dta-adrien-sandbox-dev
      #project: "{{ env_var('DBT_GCP_PROJECT') }}"
      threads: 4
      type: bigquery
  target: dev

# Using Oauth, Dbt will use by default:
# Default App Credentials locally
# Compute Engine service account in Cloud Run environments (compute@service-account)
